title: "Dr. Jane Doe - Portfolio ^& Blog" 
description: "Personal website ^& blog for an early career academic. Showcasing research, publications, and creative projects in a dark minimalist style inspired by Gitfolio." 
baseurl: "" 
url: "https://yourusername.github.io" 
markdown: kramdown 
theme: minima 
dark_theme: true 
plugins: 
  - jekyll-feed 
